/**
 * Lightweight volume catalogue for list pages (home, encyclopedia index,
 * sitemap). Generated by scripts/gen-volume-index.mjs from the volume_NN.ts
 * files — never edit volumeIndex.json by hand. Keeps ~1.5 MB of article
 * bodies out of the home-page bundle.
 */
import raw from './volumeIndex.json';
import type { Volume } from '../../../types';

export type VolumeSummary = Pick<Volume,
  'id' | 'number' | 'slug' | 'title' | 'subtitle' | 'overview' | 'summary' | 'category' |
  'lastUpdated' | 'heroImage' | 'cardImage' | 'keywords' | 'articleLink' | 'youtubeLink' |
  'youtubeStatus' | 'featured'> & {
  tableCount: number;
  faqCount: number;
  /** compatibility shim so `volume.faq?.length` keeps working */
  faq: { length: number };
  /** compatibility shim so `vol.content?.tables?.length` keeps working */
  content: { tables: { length: number } };
};

export const VOLUME_INDEX: VolumeSummary[] = (raw as any[]).map((v) => ({
  ...v,
  content: { tables: { length: v.tableCount } },
  faq: { length: v.faqCount },
}));
