
export default [
  { title: "All Bible Stories", overview: "The unified metanarrative of Scripture tracing redemption from Eden to the New Jerusalem." },
  { title: "All Biblical Numerology", overview: "A data-first library of Bible numbers: counts, patterns, and structural motifs." },
  { title: "All Big Denominations & Their Differences", overview: "Exploring the various Christian denominations and their unique beliefs and practices." },
  { title: "Angels, Demons, Beasts & Monsters in the Bible", overview: "The supernatural hierarchy and prophetic creatures mentioned in the scriptures." },
  { title: "Apologetics: 40 Critical Questions", overview: "Defending the faith with reason and revelation against modern objections." },
  { title: "Apostle's Creed", overview: "The pattern of sound teaching and the foundational confession of the Christian faith." },
  { title: "Ark of Covenant and other Biblical Relics", overview: "Sacred objects: the history of the Ark, Passion relics, and their modern preservation sites." },
  { title: "Baptism, Sacraments & Circumcision", overview: "The covenant signs and markers of identity in the Old and New Testaments." },
  { title: "Bible Book Writers", overview: "Traditional and scholarly views on the human authors of the 66 canonical books." },
  { title: "Biblical Creation vs Scientific Creation", overview: "A side-by-side comparison of Genesis and modern scientific models of origins." },
  { title: "Biblical Maps", overview: "A visual atlas of sacred history, from the Exodus to the missionary journeys of Paul." },
  { title: "Book of Revelation", overview: "A comprehensive exploration of the structure, symbolism, and prophecy of the final book." },
  { title: "Christianity in South Asia (India & Pakistan)", overview: "From the Apostle Thomas to the modern era, exploring the rich heritage of the subcontinent." },
  { title: "Christmas History", overview: "The incarnation of the Word and the historical evolution of the nativity feast." },
  { title: "Comparative Religion", overview: "Contrasting Christianity with other world religions through core claims and sacred texts." },
  { title: "Complete Christian Theology Map", overview: "A visual and textual map connecting every major doctrine into a unified worldview." },
  { title: "Crusades — Historical + Theological Analysis", overview: "An unbiased exploration of the military-religious campaigns from history and theology." },
  { title: "Early Church Fathers & Councils", overview: "How early leaders and global councils shaped the core doctrines of the faith." },
  { title: "Easter & Resurrection", overview: "The cornerstone of the Christian faith explored through history and theology." },
  { title: "Family Tree: Adam → Jesus", overview: "Traces the genealogy of the Messiah through both legal and biological lines." },
  { title: "Forbidden Knowledge & the Watchers", overview: "Ancient teachings attributed to fallen beings and their modern ethical parallels." },
  { title: "Guide to Christian Living", overview: "Living a spiritually strong, ethical, and mission-centered life in a modern world." },
  { title: "Heaven & Hell", overview: "What the Bible actually says about the afterlife—places, states, imagery, and hope." },
  { title: "History of All 12 Disciples", overview: "The lives, global missions, and legacy of the original twelve apostles after the Resurrection." },
  { title: "Holy Communion", overview: "Theological and historical exploration of the sacred meal of remembrance." },
  { title: "How The World Populated After Abel's Death", overview: "Understanding early human multiplication based on the biblical record." },
  { title: "Jesus Is God (Full References OT + NT)", overview: "A comprehensive biblical defense of the divinity of Jesus Christ." },
  { title: "Lord's Prayer", overview: "A pattern for kingdom-centered prayer and relationship with the Heavenly Father." },
  { title: "Messianic Prophecies", overview: "Over 300 promises in the Old Testament fulfilled in the person of Jesus." },
  { title: "Names of God", overview: "Revealing the identity and nature of the Father through His scriptural names." },
  { title: "Names of Jesus", overview: "Exploring the titles and names of the Son and what they reveal about Him." },
  { title: "Non-Canonical Books & Canon Differences", overview: "Why some books were included in the Bible while others were excluded." },
  { title: "Not Biblical Quotes or Sayings", overview: "Common sayings wrongly attributed to the Bible and their true origins." },
  { title: "Original Scripture Languages", overview: "A gateway to reading the Bible in Hebrew, Aramaic, and Koine Greek." },
  { title: "Primeval World Timeline & Ancient Civilizations", overview: "Reconciling Genesis with archaeology, ancient city-building, and shared global flood traditions." },
  { title: "Psalm Authors", overview: "The writers, musicians, and poets behind the Book of Psalms." },
  { title: "Revelation Judgments Timeline", overview: "A chronological guide to the Seals, Trumpets, and Bowls of the Apocalypse." },
  { title: "Sermon on the Mount", overview: "Jesus' greatest Kingdom manifesto found in Matthew 5–7." },
  { title: "Seven Last Words of Jesus", overview: "A devotional and theological look at the final statements from the cross." },
  { title: "Systematic Theology Subjects", overview: "An overview of major topics: Soteriology, Ecclesiology, and more." },
  { title: "Ten Commandments & OT Laws", overview: "Breakdown of the Moral, Civil, and Ceremonial laws given at Sinai." },
  { title: "The Magi", overview: "Historical and theological exploration of the 'Wise Men' from the East." },
  { title: "True Worship vs False Worship", overview: "Contrasting what pleases God with religious hypocrisy and empty ritual." },
  { title: "Vatican and its History", overview: "From the Early Church to the modern Sovereign City-State." },
  { title: "World's All Big Churches", overview: "A study of the world's most significant historical and modern church structures." },
  { title: "1-Year Sermon Guide (52 Gen-Z Topics)", overview: "A year-long guide of sermon topics relevant to a younger generation, focusing on modern challenges." }
];
